# config-management.yaml
applySpecVersion: 1
spec:
  configSync:
    enabled: true
	  sourceFormat: hierarchy
    syncRepo: https://github.com/nsabine/anthos-config-mgmt-demo
    syncBranch: main
    secretType: none
    policyDir: policy
  policyController:
    enabled: true
  hierarchyController:
     enabled: false
