apiVersion: "v1"
kind: "Service"
metadata:
  name: "nginx-service"
  namespace: "nginx"
  labels:
    app: "nginx"
    app.kubernetes.io/managed-by: "configmanagement.gke.io"
    configsync.gke.io/declared-version: "v1"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "nginx"
  type: "ClusterIP"
